# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main, github-actions ]
  pull_request:
    branches: [ main, github-actions ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest] # skip Windows for now, since it always fails, https://github.com/pytest-dev/pytest/issues/8191
        python-version: [3.7]
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pipenv
      run: |
        pip install pipenv
    - name: Cache pipenv
      id: cache-pipenv
      uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-python-${{ matrix.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-python-${{ matrix.python-version }}-pipenv-
    - name: Install Kassia dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install --deploy --dev
    - name: Lint
      run: |
        pipenv run isort . --recursive --diff
        pipenv run flake8
    - name: Install pytest dependencies # needed for tests using diff-pdf-visually
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install -qq -o=Dpkg::Use-Pty=0 imagemagick
          sudo apt-get install -qq -o=Dpkg::Use-Pty=0 poppler-utils
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install --no-progress imagemagick
          choco install --no-progress poppler
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install -q imagemagick
          brew install -q poppler
        else
          echo "$RUNNER_OS not supported"
        fi
    - name: Test with pytest
      run: | 
        pipenv run pytest
